apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ollama-deployment
  labels:
    app.kubernetes.io/name: ollama
    helm.sh/chart: ollama-chart-0.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ollama
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ollama
    spec:
      containers:
        - name: ollama-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - "ollama run gemma:2b"

