name: Pull Request Action

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print PR Information
      run: |
        echo "Pull Request Number: ${{ github.event.pull_request.number }}"
        echo "Pull Request Title: ${{ github.event.pull_request.title }}"
        echo "Pull Request Author: ${{ github.event.pull_request.user.login }}"
